UPDATE Lead_Header  SET STATUS = 'REJECTED'   WHERE Customer_Profile_Id IN(SELECT CP.CUSTOMER_PROFILE_ID FROM Customer_Profile CP  WHERE CP.CUSTOMER_CODE  = '1173930' );

UPDATE Customer_Profile SET CUSTOMER_STATUS = 'INACTIVE'  WHERE  CUSTOMER_CODE  = '1173930';
